In [24]:
lanth=int (input ("leanth of the pass: "))
pas=""
for x in range (int(lanth/2)):
    pas+=random.choice(aa)
    pas
for x in range (int(1)):
    pas+=str(np.random.randint(0000,9999))
print(pas)
print (len(pas))

leanth of the pass: 9
tfiq4370
8


In [9]:
aa="abcdefghijklmnnopqrstuvwxyz@#$%&*"

In [5]:
import random

In [8]:
import numpy as np

In [29]:
lanth//2

4

In [22]:
len(pas)

8

In [1]:
import numpy as np

In [2]:
b=np.random .rand(100000)

In [3]:
%%timeit sum(b)
s=0
for x in b:
    s+=x

15.6 ms ± 2.26 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit np.sum (b)

38.3 µs ± 804 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
import pandas as pd

In [6]:
d=pd.Series([1,2,3],index=['a','b','c'])

In [7]:
grads_dict ={'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [8]:
g= pd.Series([1,2,3],index=['a','b','c'])


In [12]:
g

a    1
b    2
c    3
dtype: int64

In [13]:
g.values

array([1, 2, 3], dtype=int64)

In [14]:
g.index

Index(['a', 'b', 'c'], dtype='object')

In [16]:
sg=['A','B','C','D','E','F','G','E']

In [18]:
type(sg[1])

str

In [43]:
pd.Series(nm,index=sg)

ValueError: Length of values (24) does not match length of index (8)

In [33]:
nm=np.random.rand(24)*10

In [34]:
nm

array([7.63794711, 7.68155544, 8.24083871, 4.79813679, 2.02079367,
       7.73048125, 2.01182212, 7.27623719, 3.21381949, 5.16908472,
       5.86439576, 7.91261745, 3.61741142, 8.48374654, 4.73479573,
       4.53268227, 1.17692908, 3.30045932, 2.65177292, 1.24260457,
       1.05029955, 0.10722965, 1.18350289, 5.31692883])

In [35]:
nm=np.round(nm)

In [36]:
nm

array([8., 8., 8., 5., 2., 8., 2., 7., 3., 5., 6., 8., 4., 8., 5., 5., 1.,
       3., 3., 1., 1., 0., 1., 5.])

In [40]:
gg=nm.reshape(8,3)

In [41]:
gg

array([[8., 8., 8.],
       [5., 2., 8.],
       [2., 7., 3.],
       [5., 6., 8.],
       [4., 8., 5.],
       [5., 1., 3.],
       [3., 1., 1.],
       [0., 1., 5.]])

In [29]:
type(sg)

list

In [30]:
len(sg)

8

In [19]:
ss=np.round(np.random.rand(8)*10)

In [20]:
ss

array([1., 3., 1., 1., 9., 8., 2., 2.])

In [49]:
ss[0]=5

In [50]:
ss

array([5., 4., 8., 4., 6., 1., 5., 1.])

In [1]:
ss[[1,-1,-2]]=[2,7,9]

NameError: name 'ss' is not defined

In [59]:
ss

array([5., 2., 8., 4., 6., 1., 9., 7.])

In [95]:
m=pd.Series(ss,index=sg)

In [97]:
m

A    5.0
B    2.0
C    8.0
D    4.0
E    6.0
F    1.0
G    9.0
E    7.0
dtype: float64

In [98]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [99]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [101]:
m.index

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'E'], dtype='object')

In [103]:
D = pd.DataFrame({'Marks':marks,'Grades':m['A':'D']})

In [147]:
D

Marks  Grades  ScaledMarks
A     85     5.0    94.444444
B     75     2.0    83.333333
C     65     8.0    72.222222
D     55     4.0    61.111111

In [148]:
D[0]

KeyError: 0

In [105]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   5.0   2.0   8.0   4.0

In [108]:
D.add

<bound method flex_arith_method_FRAME.<locals>.f of    Marks  Grades
A     85     5.0
B     75     2.0
C     65     8.0
D     55     4.0>

In [3]:
g=D.values[0:2,1]

NameError: name 'D' is not defined

In [138]:
g

array([5., 2.])

In [139]:
g.ndim

1

In [135]:
type(g)

numpy.ndarray

In [113]:
m['A']

5.0

In [114]:
marks['A']

85

In [118]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [119]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [121]:
marks['A']=95

In [123]:
D.marks

AttributeError: 'DataFrame' object has no attribute 'marks'

In [122]:
marks

A    95
B    75
C    65
D    55
dtype: int64

D

In [143]:
    D['ScaledMarks'] = 100*(D['Marks']/90)
D


Marks  Grades  ScaledMarks
A     85     5.0    94.444444
B     75     2.0    83.333333
C     65     8.0    72.222222
D     55     4.0    61.111111

In [144]:
D['ScaledMarks']

A    94.444444
B    83.333333
C    72.222222
D    61.111111
Name: ScaledMarks, dtype: float64

In [146]:
D['Marks']

A    85
B    75
C    65
D    55
Name: Marks, dtype: int64

In [4]:
D

NameError: name 'D' is not defined

In [150]:
D.rename(columns={'Marks':'no','Grades':'point'})

no  point  ScaledMarks
A  85    5.0    94.444444
B  75    2.0    83.333333
C  65    8.0    72.222222
D  55    4.0    61.111111

In [160]:
del D['ScaledMarks']

In [161]:
D

Marks  Grades
A     85     5.0
B     75     2.0
C     65     8.0
D     55     4.0

In [162]:
G = D[D['Marks']>70]

In [163]:
G

Marks  Grades
A     85     5.0
B     75     2.0

In [164]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [165]:
A

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [167]:
A.fillna("nall")

a  b     c
0   1.0  4  nall
1  nall -3   9.0

In [169]:
A.rename(columns={'a':"aaa",'b':"ddd" })

aaa  ddd    c
0  1.0    4  NaN
1  NaN   -3  9.0

In [170]:
A = pd.Series(['a','b','c'],index=[1,3,5])

In [171]:
A

1    a
3    b
5    c
dtype: object

In [178]:
A[[1,3]]

1    a
3    b
dtype: object

In [180]:
A[2:10]

5    c
dtype: object

In [194]:
D.iloc[1,:]

Marks     75.0
Grades     2.0
sky        2.0
Name: B, dtype: float64

In [192]:
D['sky']=[1,2,3,4]

In [189]:
i= 100*(D['Marks']/90)

In [190]:
i

A    94.444444
B    83.333333
C    72.222222
D    61.111111
Name: Marks, dtype: float64

In [1]:
type(i)

NameError: name 'i' is not defined

In [193]:
D

Marks  Grades  sky
A     85     5.0    1
B     75     2.0    2
C     65     8.0    3
D     55     4.0    4

In [197]:
D.drop('B','d')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21624\393343299.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  D.drop('B','d')


ValueError: No axis named d for object type DataFrame

In [12]:
nums=[1,2,4]
target=6
for x in range(len(nums)):
            for y in range (x+1,len(nums)):
                sum=x+y
                if sum==target:
                    x
                    y

In [6]:
nums=[1,2,4]
taret=6
for x in range(len(nums)):
            for y in range (x+1,len(nums)):
                sum=nums[x]+nums[y]
                

In [7]:
sum

6

In [14]:
y

2

In [5]:
nums[1]

2

In [8]:
l1 = [2,4,3]
l2 = [5,6,4]

In [9]:
l1[::-1]

[3, 4, 2]

In [10]:
l2[::-1]

[4, 6, 5]

In [20]:
s=0
for x in (l1[::-1]):
    d=int(''.join(map(str,l2[::-1])))


In [22]:
d=int(''.join(map(str,l1[::-1])))

In [23]:
d

342

In [24]:
sum=int(''.join(map(str,l1[::-1])))+int(''.join(map(str,l2[::-1])))

In [25]:
sum

807

In [4]:
pd.to_datetime(1490195805, unit='s')
pd.to_datetime(1490195805433502912, unit='ns')


Timestamp('2017-03-22 15:16:45.433502912')

In [2]:
import pandas as pd

In [26]:

pd.to_datetime(1676872344319,)

Timestamp('1970-01-01 00:27:56.872344319')

In [29]:
pd.to_datetime(1676872329986)

Timestamp('1970-01-01 00:27:56.872329986')

In [1]:
import numpy as np


In [5]:
a=np.array??

In [ ]:
a=np.array

In [3]:
a

array(10)

In [39]:
a=np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1=a[::2]

In [42]:
a1

array([0, 2, 4, 6, 8])

In [43]:
a2=a[1::2]

In [44]:
a2

array([1, 3, 5, 7, 9])

In [26]:
a1+a2

array([ 1,  5,  9, 13, 17])

In [25]:
ass

array([ 1,  5,  9, 13, 17])

SyntaxError: invalid syntax (3710835044.py, line 1)

In [31]:
np.stack((a1,a2))

array([[ 2,  8, 14, 20, 26],
       [ 1,  3,  5,  7,  9]])

In [46]:
a2

array([1, 3, 5, 7, 9])

In [45]:
a1

array([0, 2, 4, 6, 8])

In [49]:
a=np.concatenate((a1,a2))

In [50]:
a

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [52]:
k=np.sort(a)

In [53]:
len(k)

10

In [55]:
10//2

5

In [56]:
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
nums1=np.array([1,3,5,9])
nums2=np.array([2,4,8,10])
a=np.concatenate((nums1,nums2))
b =np.sort(a)
if len(b)%2==0:
    s=(b[len(b)//2]+b[(len(b)//2)-1])/2
else:
    s=b[len(b)//2]

In [107]:
s

4.5

In [65]:
a=np.concatenate((nums1,nums2))

In [66]:
a

array([1, 3, 2])

In [78]:
b

array([ 1,  2,  3,  4,  5,  8,  9, 10])

In [88]:
b[len(b)//2]

5

In [84]:
k

8.5

In [103]:

    s=(b[len(b)//2]+b[(len(b)//2)-1])/2

In [104]:
s

4.5

In [100]:
s/2

4.5

In [108]:
s = "babad"

In [113]:
s1=s[::-1]

In [114]:
s1

'dabab'

In [121]:
s1[0]    

'd'

In [122]:
s[0]

'b'

In [124]:
j=""
for x in range (len(s)):
    if (s[x-1]==s[-x]):
        j[x-1]=s[x-1]
        j[-x]=s[-x]

TypeError: 'str' object does not support item assignment

In [123]:
len (s)

5

In [125]:
x=1
s[x]

'a'

In [126]:
s[-x]

'd'

In [129]:
j[x-1]="s"

TypeError: 'str' object does not support item assignment

In [128]:
j=""

In [149]:
maxlen=0
for i in range (len(s)):
    for  j in range (i+1,len(s)+1):
        cond =s[i:j]
        if cond ==cond[::-1] and len(cond)>maxlen:
            out=cond
            maxlen=len(cond)

In [150]:
cond

'd'

In [138]:
s

'babad'

In [174]:
s[4:5]

'd'

In [172]:
for i in range (5,6):
    i

In [173]:
i

5

In [151]:
out 

'bab'

In [159]:
for i in range (5):
    for  j in range (i+1,len(s)+1):
        cond =s[i:j]

In [178]:
cond

'd'

In [176]:
for x in range (len ( s)):
    a=s[x]

In [177]:
a

'd'

In [179]:
cond[::-1]

'd'

In [2]:
maxlen=0
for i in range (len(s)):
    for  j in range (i+1,len(s)+1):
        cond =s[i:j]
        if cond ==cond[::-1] and len(cond)>maxlen:
            out=cond
            maxlen=len(cond)

In [3]:
s = "babad"

In [4]:
out 

'bab'

In [5]:
import numpy as np 

In [35]:
a=np.random.beta(np.arange(100),0.2)


ValueError: a <= 0

In [37]:
a

array([ 1.00000000e+01, -4.00491805e-02,  1.42510924e+00,  2.52112335e+00,
        3.40632448e+00,  5.21450056e+00,  6.04696948e+00,  5.92707520e+00,
        9.78779880e+00,  7.88961036e+00,  1.02113752e+01,  9.91653474e+00,
        1.20067166e+01,  1.29194202e+01,  1.33798256e+01,  1.50357799e+01,
        1.78723484e+01,  1.62495931e+01,  1.85912761e+01,  1.84823390e+01,
        1.98879516e+01,  2.12597710e+01,  2.28648344e+01,  2.24526345e+01,
        2.34001472e+01,  2.48074338e+01,  2.71406571e+01,  2.67660921e+01,
        2.73784366e+01,  2.86857546e+01,  3.01575958e+01,  3.09597223e+01,
        3.24067569e+01,  3.29907921e+01,  3.28865157e+01,  3.61384483e+01,
        3.53356994e+01,  3.60912939e+01,  3.91368158e+01,  3.90471038e+01,
        3.80958352e+01,  4.12611918e+01,  4.09435555e+01,  4.20369322e+01,
        4.31186058e+01,  4.51175019e+01,  4.62357891e+01,  5.00299776e+01,
        4.85607367e+01,  4.87096068e+01,  5.19250484e+01,  5.10141382e+01,
        5.13310139e+01,  

In [38]:
a[0]=10

In [39]:
a

array([ 1.00000000e+01, -4.00491805e-02,  1.42510924e+00,  2.52112335e+00,
        3.40632448e+00,  5.21450056e+00,  6.04696948e+00,  5.92707520e+00,
        9.78779880e+00,  7.88961036e+00,  1.02113752e+01,  9.91653474e+00,
        1.20067166e+01,  1.29194202e+01,  1.33798256e+01,  1.50357799e+01,
        1.78723484e+01,  1.62495931e+01,  1.85912761e+01,  1.84823390e+01,
        1.98879516e+01,  2.12597710e+01,  2.28648344e+01,  2.24526345e+01,
        2.34001472e+01,  2.48074338e+01,  2.71406571e+01,  2.67660921e+01,
        2.73784366e+01,  2.86857546e+01,  3.01575958e+01,  3.09597223e+01,
        3.24067569e+01,  3.29907921e+01,  3.28865157e+01,  3.61384483e+01,
        3.53356994e+01,  3.60912939e+01,  3.91368158e+01,  3.90471038e+01,
        3.80958352e+01,  4.12611918e+01,  4.09435555e+01,  4.20369322e+01,
        4.31186058e+01,  4.51175019e+01,  4.62357891e+01,  5.00299776e+01,
        4.85607367e+01,  4.87096068e+01,  5.19250484e+01,  5.10141382e+01,
        5.13310139e+01,  

In [66]:
np.random.shuffle(ar)

In [64]:
ar=np.arange(10)

In [67]:
ar

array([3, 0, 9, 4, 6, 2, 1, 5, 8, 7])

In [50]:
a1

In [52]:
np.random.shuffle??

In [53]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([2, 9, 3, 7, 8, 5, 1, 0, 6, 4])

In [73]:
np.random.chisquare??

In [71]:
arr

array([2, 9, 3, 7, 8, 5, 1, 0, 6, 4])

In [76]:
import pandas as pd

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1719618332.py, line 1)

In [79]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [85]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [95]:
A = pd.DataFrame([{'a':1,'b':4.0},{'b':-3.0,'c':9}])

In [96]:
A

a    b    c
0  1.0  4.0  NaN
1  NaN -3.0  9.0

In [99]:
m=A.fillna("nai")

In [100]:
m

a    b    c
0  1.0  4.0  nai
1  nai -3.0  9.0

In [101]:
A.add_prefix('cal ')

cal a  cal b  cal c
0    1.0    4.0    NaN
1    NaN   -3.0    9.0

In [107]:
df = pd.Series({'A': [1, 2, 3, 4], 'B': [3, 4, 5, 6]})

In [108]:
df

A    [1, 2, 3, 4]
B    [3, 4, 5, 6]
dtype: object

In [109]:
df.add_prefix('kl')

klA    [1, 2, 3, 4]
klB    [3, 4, 5, 6]
dtype: object

In [110]:
A.add_suffix("g")

ag   bg   cg
0  1.0  4.0  NaN
1  NaN -3.0  9.0

In [111]:
A.columns

Index(['a', 'b', 'c'], dtype='object')

In [112]:
A


a    b    c
0  1.0  4.0  NaN
1  NaN -3.0  9.0

In [117]:
a=pd.array([10,20,50,40],[10,40,50,50])

TypeError: Field elements must be 2- or 3-tuples, got '10'

In [115]:
a

<IntegerArray>
[10, 20, 50, 40]
Length: 4, dtype: Int64

In [5]:
import pandas as pd
import os

In [6]:
df = pd.read_csv('mushroom.csv')


FileNotFoundError: [Errno 2] No such file or directory: 'mushroom.csv'