In [4]:
print (range(10,20).count(11))

1


In [12]:
a=int (input("job"))
print ("your marks ia {}".format(a))

job50
your marks ia 50


In [14]:
aa=10
print(f" your hhho is {aa}")

 your hhho is 10


In [20]:
import numpy as np
a=np.random.randint(5,9)

In [21]:
a

7

In [27]:
(np.random.rand(2)*100)

array([93.78884924, 63.79899897])

In [28]:
import random 

In [33]:
(random.randint??

In [34]:
random.randint(5,60)

56

In [53]:
def copjoo(x):
    low=1
    high =x
    fb=''
    while fb !="c":
        if low!=high:
            guess=random.randint(low,high)
        else:
            guess=low
    

In [1]:
def copoo(x):
    low=1
    high =x
    fb=''
    while fb !="c":
        if low!=high:
            guess=random.randint(low,high)
        else:
            guess=low
        fb=input(f'is {guess} h, l ,c')
        if fb=="h":
            high=guess-1
        elif fb=="l":
            low=guess+1
            
    print (f"you guess .\nthe currecct number is {guess} ")
            
            
            

In [2]:
random??

Object `random` not found.


In [4]:
import random

In [25]:
asd=random.choice([1,7,3,5,6])

In [26]:
asd

1

In [24]:
asd

7

In [28]:
import turtle

In [1]:
import numpy as np

In [3]:
a=np.arange(10)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b=np.random.permutation(a)

In [13]:
ss=np.random.permutation(np.arange(10))

In [14]:
ss

array([0, 7, 9, 3, 1, 6, 5, 2, 4, 8])

In [16]:
c=np.random.rand(10)

In [17]:
c

array([0.12736237, 0.70591547, 0.86542896, 0.7214904 , 0.56357215,
       0.54010786, 0.69496136, 0.92154139, 0.05042722, 0.54988823])

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ass=np.random.permutation(a)

In [20]:
ass

array([1, 3, 0, 8, 2, 5, 4, 9, 7, 6])

In [24]:
ll=ass.sort(0)

In [25]:
ll

In [2]:
f=np.random.permutation(np.arange(100))

In [3]:
f

array([19, 69, 28, 29, 97, 31, 90,  8, 80, 23, 59,  7, 24, 84, 65, 44, 79,
       14, 35, 74, 10, 21,  5, 72, 43, 62,  4, 89, 50, 36, 85, 91, 86, 60,
       78, 34, 53, 55, 64,  2, 77, 33, 16, 83, 93, 57,  3, 66, 58, 27, 76,
       98, 47, 70, 88, 63, 94, 99,  9, 30, 73, 49, 95, 11, 51, 42, 96, 17,
       32, 61, 46, 37,  1, 22, 45, 54, 40, 20, 41, 18, 75, 13,  0, 81, 39,
       87, 38, 68, 82, 67, 71, 56, 48, 26, 25, 92, 52,  6, 12, 15])

In [21]:
d=f[f<=50]

In [22]:
d

array([19, 28, 29, 31,  8, 23,  7, 24, 44, 14, 35, 10, 21,  5, 43,  4, 50,
       36, 34,  2, 33, 16,  3, 27, 47,  9, 30, 49, 11, 42, 17, 32, 46, 37,
        1, 22, 45, 40, 20, 41, 18, 13,  0, 39, 38, 48, 26, 25,  6, 12, 15])

In [23]:
d.sort()

In [24]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [25]:
d=np.random.permutation(d)

In [26]:
d

array([29, 15, 37, 20, 22, 25, 41, 39, 34,  5, 21, 46, 16, 32, 12,  8, 13,
       24, 28, 33, 19,  1, 11, 47, 14, 17, 38, 48,  7, 40, 45, 27, 18, 31,
       42, 36, 35, 50, 44,  3, 43, 49, 26,  2, 30,  9, 23, 10,  0,  4,  6])

In [27]:
dd=d[(d<10) & (d>3)]

In [30]:
dd

array([4, 5, 6, 7, 8, 9])

In [29]:
dd.sort()

In [46]:
words= ["Gefeks", "For", "Geeks"]
words.sort()

In [47]:
words

['For', 'Geeks', 'Gefeks']

In [49]:
dd.sort()

In [50]:
dd

array([4, 5, 6, 7, 8, 9])

In [51]:
 asd=(10* np.random.rand(2,2))

In [52]:
asd

array([[7.26867004, 3.23375074],
       [5.92452239, 5.65003764]])

In [53]:
asd=asd+5

In [54]:
asd

array([[12.26867004,  8.23375074],
       [10.92452239, 10.65003764]])

In [64]:
for x in asd:
    print (x)

[12.26867004  8.23375074]
[10.92452239 10.65003764]


In [69]:
q=np.round(10*np.random.rand(2,3),6)

In [70]:
q

array([[4.853708, 3.608782, 6.957693],
       [2.039112, 3.198882, 9.476526]])

In [71]:
qq=np.random.permutation(np.arange(10))

In [72]:
qq

array([3, 4, 1, 7, 2, 5, 0, 8, 6, 9])

In [77]:
qq=np.sort(qq)

In [78]:
qq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
qq[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [4]:
import pandas as pd

In [5]:
print (pd.__version__)

1.4.4


#pandas


# pandas


In [6]:
grads_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grads = pd.Series(grads_dict)

In [7]:
grads.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [32]:
s=np.random.permutation(np.arange(100))

In [33]:
import numpy as np

In [34]:
s

array([72,  1, 18, 26, 37, 31, 79, 76, 23, 36, 63, 17, 54, 99, 96, 58,  4,
       98, 39, 53, 60, 66, 61, 56, 47, 38, 84, 12, 91,  7,  6, 42, 11, 74,
       19,  2,  9, 71, 46, 86, 65, 83, 73, 78, 34, 94, 22, 90, 32, 16, 27,
       44, 77, 49, 70, 43, 41, 20, 93, 97, 88, 92,  8, 59, 40, 62, 57, 25,
       29, 33, 52, 28, 89, 14, 82, 10, 24, 80, 69, 95, 81, 85,  3, 64, 35,
       13, 48, 87, 30, 45, 51,  0,  5, 21, 75, 50, 55, 67, 68, 15])

In [41]:
d

[]

In [47]:
abc=np.arange(70,100,10)

In [48]:
abc

array([70, 80, 90])

In [110]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [116]:
nall="nall"
A

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [117]:
A.fillna(nall)

a  b     c
0   1.0  4  nall
1  nall -3   9.0

In [1]:
import numpy as np

In [4]:
a=np.arange(100)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
aaa=a.reshape(20,5)

In [14]:
aaa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [21]:
ae=aaa.sort(1)

In [22]:
ae

In [23]:
aaa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [28]:
ass=np.random.permutation(aaa[:,:])

In [29]:
ass

array([[ 5,  6,  7,  8,  9],
       [95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34],
       [50, 51, 52, 53, 54],
       [15, 16, 17, 18, 19],
       [85, 86, 87, 88, 89],
       [80, 81, 82, 83, 84],
       [55, 56, 57, 58, 59],
       [90, 91, 92, 93, 94],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29],
       [75, 76, 77, 78, 79],
       [70, 71, 72, 73, 74]])

In [26]:
ass.sort(0)

In [34]:
d=aaa[:,:2]

In [35]:
d

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21],
       [25, 26],
       [30, 31],
       [35, 36],
       [40, 41],
       [45, 46],
       [50, 51],
       [55, 56],
       [60, 61],
       [65, 66],
       [70, 71],
       [75, 76],
       [80, 81],
       [85, 86],
       [90, 91],
       [95, 96]])

In [52]:
b=d[[for x in range (d.shape[0])]]

SyntaxError: invalid syntax (2509303763.py, line 1)

In [54]:
b

array([[ 5,  6],
       [15, 16],
       [25, 26]])

In [39]:
d.size

40

In [43]:
d.shape[0]

20

In [53]:
x for x in range (d.shape[0]):
   

SyntaxError: invalid syntax (718454757.py, line 1)

In [55]:
b+=5

In [56]:
b

array([[10, 11],
       [20, 21],
       [30, 31]])

In [62]:
bb=np.round (np.random.rand(2,3)*10)

In [63]:
bb

array([[ 5.,  8.,  5.],
       [ 6.,  2., 10.]])

In [67]:
bb=bb.reshape(3,2)

In [68]:
b+bb

array([[15., 19.],
       [25., 27.],
       [32., 41.]])

In [69]:
b
bb

array([[ 5.,  8.],
       [ 5.,  6.],
       [ 2., 10.]])

In [77]:
cc=np.array([[1,2,3,],[4,5,6]])

In [78]:
dtype.cc

NameError: name 'dtype' is not defined

In [79]:
type(cc)

numpy.ndarray

In [80]:
cc.ndim

2

In [81]:
cc

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
cc.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [86]:
ca=np.array([1,2,3,4])

In [87]:
ca



array([1, 2, 3, 4])

In [89]:
np.vstack??

In [96]:
np.stack((b,bb))

array([[[10., 11.],
        [20., 21.],
        [30., 31.]],

       [[ 5.,  8.],
        [ 5.,  6.],
        [ 2., 10.]]])

In [95]:
np.vstack??

In [97]:
np.column_stack((b,bb))

array([[10., 11.,  5.,  8.],
       [20., 21.,  5.,  6.],
       [30., 31.,  2., 10.]])

In [102]:
np.hstack((b,bb))

array([[10., 11.,  5.,  8.],
       [20., 21.,  5.,  6.],
       [30., 31.,  2., 10.]])

In [1]:
import numpy as np

In [2]:
np.random .rand(10)

array([0.9275934 , 0.68321985, 0.97042696, 0.41861644, 0.47090445,
       0.1144004 , 0.19758746, 0.86932139, 0.29205467, 0.16511464])

In [3]:
import random

In [4]:
random.rand??

Object `random.rand` not found.


In [5]:
import random
import string

def generate_random_string(length):
    letters = string.ascii_uppercase
    return ''.join(random.choice(letters) for i in range(length))

# Generate a random string of length 10
random_string = generate_random_string(10)

print(random_string)

FBCKPDISTS


In [16]:
generate_random_string(10)

'SGTWQIQYIR'

In [17]:
join(random.choice(10))

NameError: name 'join' is not defined

In [47]:
aa="abcdefghijklmnopqrstuvwxyz@#$%&*"

In [53]:
random.choice(aa)

'x'

In [67]:
ab=random.randint(0,9)

In [85]:
l=np.array([])

In [82]:
for x in range (8):
    l[x]=random.choice(aa)
    x+=1
    l[x+1]=random.randint(0,9)
    x+=1
    

ValueError: invalid literal for int() with base 10: '#'

In [94]:
l[0]=random.choice(aa)

In [95]:
l=np.empty(1,dtype='U')

In [100]:
array = np.empty(1, dtype='U')

# Input a string into the array
array[0] ='Hello, world!'

In [101]:
print (array)

['H']


In [98]:
l[0]

''

In [105]:
import numpy as np

# Create an empty NumPy array with a single string element
array = np.empty(1, dtype='U')

# Input a string into the array
array[0] = "'Hello, world!'"

# Print the array
print(array)


["'"]


In [108]:
l=np.array(50)

In [110]:
l[10]=

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [114]:
l.ndim

0

In [ ]:
lanth=int (input ("leanth of the pass"))
pas=""
for x in range (2):
    pas+=random.choice(aa)
print(pas)

In [ ]:
lanth=int (input ("leanth of the pass"))
pas=""
for x in range (lanth):
    pas+=random.choice(aa)
print(pas)