In [28]:
def abcd (A,B):
    if isinstance(A,(int)) and isinstance (B,(int ,float)):
        print ((A**2)*(B*1))
    else:
        print("error")

In [29]:
abcd(10,"hi")

error


In [30]:
def g(c,f,t):
    d=c+f+t
    return d

In [31]:
g(c=44,f=10,t=50)

104

In [5]:
 numbers = [1, 2, 3, 4, 2, 5]

# check if numbers is instance of list
result = isinstance(numbers,list)
print(result)


True


In [33]:
a=10
isinstance(int,10)

TypeError: isinstance() arg 2 must be a type or tuple of types

In [34]:
help(isinstance)

Help on built-in function isinstance in module builtins:

isinstance(obj, class_or_tuple, /)
    Return whether an object is an instance of a class or of a subclass thereof.
    
    A tuple, as in ``isinstance(x, (A, B, ...))``, may be given as the target to
    check against. This is equivalent to ``isinstance(x, A) or isinstance(x, B)
    or ...`` etc.



In [35]:
for i in range (5,0,-1):
    for j in range (i):
        print ("*",end=" ")
    for k in range (i+1):
        print ("",end="*")
    print ()

* * * * * ******
* * * * *****
* * * ****
* * ***
* **


In [36]:
for i in range (5):
    for j in range (i,5):
        print ("* ",end=(""))
        print ("")
    for k in range (i+1):
        print ("*",end=" ")
    print ("")

* 
* 
* 
* 
* 
* 
* 
* 
* 
* 
* * 
* 
* 
* 
* * * 
* 
* 
* * * * 
* 
* * * * * 


In [37]:
def j (*asd):
    s=0
    for x in asd:
        s=s+x 
        print (s)
    print (s)

In [38]:
j(10,20,40,50,6,7,400)

10
30
70
120
126
133
533
533


In [39]:
j(10,20,40,50,6,7,400)
print (len (asd))

10
30
70
120
126
133
533
533


NameError: name 'asd' is not defined

In [40]:
def i(*ji ):
    print (len(ji))
    for x in ji:
        if not  isinstance(x,str):
            print (x)
    print ()
    for x in ji:
        if isinstance(x,str):
            print (x)
    

In [41]:
i(10,20,"jii",60,30,"41","lala ")

7
10
20
60
30

jii
41
lala 


In [42]:
def ggg(**s):
    for x in range  (len(s)):
        print (x,)

In [43]:
ggg(a="hi",b="ji",k=10,ji=55,fff="lll")

0
1
2
3
4


In [44]:
def myarg(*arg):
    for x in range (len(arg)): 
        print (x,arg[x])

In [45]:
myarg(1,5,1,4,2)


0 1
1 5
2 1
3 4
4 2


In [46]:
def ggg(**s):
    for x in s:
        print (x,s[x])
        

In [47]:
ggg(a="hi",b="ji",k=10,ji=55,fff="lll")

a hi
b ji
k 10
ji 55
fff lll


In [48]:
a='this is py '
b="by the boos "
c=a+b
print (c)
d=c+str(10)
print (d)

this is py by the boos 
this is py by the boos 10


In [49]:
l=input("hi")
m=int (l)+10
print (m)

hi


ValueError: invalid literal for int() with base 10: ''

In [50]:
A="this is python"


In [51]:
help(A.center)


Help on built-in function center:

center(width, fillchar=' ', /) method of builtins.str instance
    Return a centered string of length width.
    
    Padding is done using the specified fill character (default is a space).



In [52]:
A.center(10,hi='k')

TypeError: str.center() takes no keyword arguments

In [53]:
A.encode?


In [54]:
print ("asd" not in "asadfgh")

True


In [55]:
print ("asd"in "asdfgh")

True


In [56]:
print ("we are \"jaint\" ")

we are "jaint" 


In [57]:
print ("we are 'jainr '")

we are 'jainr '


In [58]:
listt=[ x for x in range (10)]

In [59]:
listt


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
listt.append(5000)

In [61]:
d1={"a":1,"b":2,"c":3}

In [62]:
d2={"D":4,"e":5,"f":listt}

In [63]:
d1.update(d2)

In [64]:
d1

{'a': 1,
 'b': 2,
 'c': 3,
 'D': 4,
 'e': 5,
 'f': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5000]}

In [65]:
for x in (d1):
    print (x,(d1[x]**2)+3)

a 4
b 7
c 12
D 19
e 28


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [66]:
d1.update(d2)

In [67]:
d1

{'a': 1,
 'b': 2,
 'c': 3,
 'D': 4,
 'e': 5,
 'f': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5000]}

In [68]:
d1["f"]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5000]

In [69]:
d1["f"][-]

SyntaxError: invalid syntax (1315667095.py, line 1)

In [70]:
ls=[10,20,"hi",30,d1]

In [71]:
ls

[10,
 20,
 'hi',
 30,
 {'a': 1,
  'b': 2,
  'c': 3,
  'D': 4,
  'e': 5,
  'f': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5000]}]

In [72]:
ls[-1]["f"]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5000]

In [73]:
s={x**x for x in range (5)}

In [74]:
s

{1, 4, 27, 256}

In [75]:
d={}
std=input ("namr ")
ide=input("n")

namr 
n


In [76]:
d

{}

In [77]:
def get():
    D={}
    while True:
        stud=input ("id")
        marks=input ("seperate by ','")
        morestd=input ("no in small leter ")
        if stud in D:
            print ("already entered  ")
        else :
            D[stud]=marks.split(",")
        if morestd.lower()=="no":
            return D

In [ ]:
get()

id
seperate by ','
no in small leter 
id
seperate by ','
no in small leter 
already entered  
id
seperate by ','
no in small leter 
already entered  
id
seperate by ','
no in small leter 
already entered  
id
seperate by ','
no in small leter 
already entered  
id
seperate by ','
no in small leter 
already entered  
id


In [ ]:
D

In [ ]:
D={}
        stud=input ("id")
        marks=input ("seperate by ','")
        morestd=input ("no in small leter ")
        if stud in D:
            print ("already entered  ")
        else :
            D[stud]=marks.split(",")
        if morestd.lower()=="no":
            return D

In [ ]:
s={x**1 for x in range (10)}

In [ ]:
s

In [ ]:
print ("hi thid si r "+"noha in ab")

In [ ]:
def get():
    D={}
    while True:
        stud=input ("id")
        marks=input ("seperate by ','")
        morestd=input ("no in small leter ")
        if stud in D:
            print ("already entered  ")
        else :
            D[stud]=marks.split(",")
        if morestd.lower()=="no":
            return D

In [ ]:
get()

In [ ]:
def avgm(D):
    avarage={}
    for x in D:
        l=D[x]
        sum=0
        for marks in l:
            s=s+int(marks)
            avarage[x]=s/len(l)
        return avarage 

In [ ]:
avgm()

In [ ]:
D

In [ ]:
print (get(D))

In [ ]:
input Numpy as np

In [ ]:
import numpy as np

In [ ]:
a=np.random.rand(2,3,4,5)

In [ ]:
print (a)

In [ ]:
a[1,2,2,3]

In [ ]:
 print(a[::2,:])

In [ ]:
b=a[]

In [ ]:
print (b)

In [ ]:
import numpy as np

In [ ]:
a=np .random.randn(1)

In [16]:
a=np .random.randn

In [17]:
a

<function RandomState.randn>

In [18]:
 a.ndim 

AttributeError: 'builtin_function_or_method' object has no attribute 'ndim'

In [19]:
import numpy as np

In [20]:
A=np. array([[1,2,3],[2,5,4]])

In [21]:
a

<function RandomState.randn>

In [22]:
A

array([[1, 2, 3],
       [2, 5, 4]])

In [23]:
A[0,2]

3

In [24]:

A[1,2]

4

In [25]:
A.ndim(1)

TypeError: 'int' object is not callable

In [26]:
a=np.random.randn(2,3)

In [27]:
a

array([[ 0.18454816, -0.48294786, -0.90583736],
       [ 0.07923613,  0.65636246, -0.76983336]])

In [ ]:
type(a)

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
a.shape

In [ ]:
a.shape[0]

In [ ]:
D=np.arange(10)

In [15]:
D

NameError: name 'D' is not defined

In [ ]:
D.ndim 

In [ ]:
D.size

In [ ]:
k=D.permutation.reshape(2,5)

In [ ]:
k

In [ ]:
e=np.random.permutation(10)

In [ ]:
e

In [ ]:
h=e.reshape(2,5)

In [ ]:
h

In [ ]:
g=np.random.permutation(100).reshape(2,5,10)

In [ ]:
g

In [ ]:
g.size

In [ ]:
g.ndim 

In [ ]:
g[0,0,2]=111


In [ ]:
g

In [ ]:
print(g[0,0,2])

In [ ]:
r=np.random.rand(2,3,5)

In [ ]:
r

In [ ]:
r.ndim 

In [ ]:
s=np.random.rand(2)

In [ ]:
s

In [ ]:
s.ndim


In [ ]:
r

In [ ]:
aw=r.reshape(30)

In [ ]:
aw

In [ ]:
aw.ndim

In [ ]:
r.shape

In [25]:
g

NameError: name 'g' is not defined

In [26]:
g.shape

NameError: name 'g' is not defined

In [27]:
ad=g.reshape(100)

NameError: name 'g' is not defined

In [28]:
ad

NameError: name 'ad' is not defined

In [29]:
ad

NameError: name 'ad' is not defined

In [30]:
ad.size

NameError: name 'ad' is not defined

In [31]:
ad.ndim 

NameError: name 'ad' is not defined

In [32]:
ad.zeros

NameError: name 'ad' is not defined

In [33]:
np.zeros?


In [34]:
np.zeros((2,3), dtype=[('x', 'i4'), ('y', 'i4')])

array([[(0, 0), (0, 0), (0, 0)],
       [(0, 0), (0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

In [35]:
print ('x')

x


In [36]:
aa=np.arange(100)

In [37]:
aa[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [38]:
aa[3]=1111

In [39]:
aa

array([   0,    1,    2, 1111,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99])

In [40]:
d=aa[::-1]

In [41]:
d

array([  99,   98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
         88,   87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
         77,   76,   75,   74,   73,   72,   71,   70,   69,   68,   67,
         66,   65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
         55,   54,   53,   52,   51,   50,   49,   48,   47,   46,   45,
         44,   43,   42,   41,   40,   39,   38,   37,   36,   35,   34,
         33,   32,   31,   30,   29,   28,   27,   26,   25,   24,   23,
         22,   21,   20,   19,   18,   17,   16,   15,   14,   13,   12,
         11,   10,    9,    8,    7,    6,    5,    4, 1111,    2,    1,
          0])

In [42]:
d[-4]

1111

In [43]:
idz=np.argwhere(d==1111)

In [44]:
idz

array([[96]], dtype=int64)

In [45]:
idz[0,0]

96

In [46]:
d[96]=96

In [47]:
d

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4, 96,  2,  1,  0])

In [48]:
 aa=np.random.rand(2,3)

In [49]:
aa

array([[0.27330333, 0.06470478, 0.74913972],
       [0.75402816, 0.09262361, 0.11879506]])

In [50]:
ass=10*aa

In [51]:
ass

array([[2.73303333, 0.64704782, 7.4913972 ],
       [7.54028164, 0.92623606, 1.18795057]])

In [52]:
zz=np.round(10*np.random.rand(2,5))

In [53]:
zz

array([[5., 3., 8., 2., 8.],
       [6., 2., 9., 6., 8.]])

In [54]:
ddd=10*np.random.rand(2,5)

In [55]:
ddd

array([[7.98191893, 1.06457187, 5.02957587, 1.82852878, 1.16849459],
       [6.83961503, 6.76464357, 0.0344979 , 4.1970208 , 5.90850081]])

In [56]:
ccc=np.round(ddd)

In [57]:
ccc

array([[8., 1., 5., 2., 1.],
       [7., 7., 0., 4., 6.]])

In [58]:
np.arange(10,50).reshape(4,2,5)

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [59]:
d.size

100

In [60]:
dd=d.reshape(5,20)

In [62]:
dd.ndim

2

In [63]:
dd

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84,
        83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
        63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44,
        43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24,
        23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        96,  2,  1,  0]])

In [61]:
dd[0,::-1]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

In [64]:
dd

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84,
        83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
        63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44,
        43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24,
        23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        96,  2,  1,  0]])

In [65]:
dd.ndim

2

In [66]:
dd[:,0]

array([99, 79, 59, 39, 19])

In [67]:
a

array([1, 2, 3, 4, 5, 8, 6])

In [68]:
A

NameError: name 'A' is not defined

In [69]:
aa

array([[0.27330333, 0.06470478, 0.74913972],
       [0.75402816, 0.09262361, 0.11879506]])

In [70]:
cc

NameError: name 'cc' is not defined

In [71]:
d

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4, 96,  2,  1,  0])

In [72]:
nn=np.random.rand(3,3)

In [73]:
nn

array([[0.51396159, 0.42870657, 0.75316318],
       [0.65086376, 0.91771704, 0.74415286],
       [0.40206048, 0.18962698, 0.83764883]])

In [74]:
nn

array([[0.51396159, 0.42870657, 0.75316318],
       [0.65086376, 0.91771704, 0.74415286],
       [0.40206048, 0.18962698, 0.83764883]])

In [75]:
import numpy.linalg as la

In [76]:
la.inv(nn)

array([[ 19.51361788,  -6.72470399, -11.57135352],
       [ -7.64860628,   3.97048961,   3.34984937],
       [ -7.63478956,   2.32893036,   5.98957701]])

In [77]:
la.inv(12)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,],dtype='f')

In [7]:
a

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
aa=np. arange(3,3,dtype ='f')

In [ ]:
aa

In [ ]:
print (aa)

In [1]:
type (aa)

NameError: name 'aa' is not defined

In [2]:
import numpy as np

In [3]:
a=np.array((1,2,3,4,5,8,6))

In [4]:
a

array([1, 2, 3, 4, 5, 8, 6])

In [5]:
dtype.a

NameError: name 'dtype' is not defined

In [6]:
type(a)

numpy.ndarray

In [12]:
np.argwhere(a==8)[0]

array([5], dtype=int64)

In [8]:
a[5]

8

In [13]:
s=np.arange(100)

In [14]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
s[95]=111

In [16]:
s

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94, 111,  96,  97,  98,  99])

In [21]:
aa=np.argwhere(s==111)[0]

In [18]:
aa

95

In [22]:
np.argwhere??

In [88]:
dd=s.reshape(5,20)

In [89]:
dd

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94, 111,  96,  97,  98,  99]])

In [87]:
s

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94, 111,  96,  97,  98,  99])

In [90]:
dd[2,0]

40

In [92]:
dd[2:4,0:2]

array([[40, 41],
       [60, 61]])

In [95]:
asd=dd[2,::-1]

In [96]:
asd

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40])

In [106]:
asd[]

array([], dtype=int32)